mnist/urls.py
from django.urls import path
from . import views

app_name = 'mnist'

urlpatterns = [
    path('', views.UploadView.as_view(), name='upload'),
    path('paint/', views.PaintView.as_view(), name='paint'),
]

project5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mnist.urls')),
]

mnist/models.py
from django.db import models

# Create your models here.

mnist/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    file = forms.ImageField(label='画像ファイル')

mnist/views.py
import base64
from io import BytesIO
from django.shortcuts import render
from django.views import generic
from .forms import ImageUploadForm
from .lib import predict
import numpy as np
from PIL import Image


class UploadView(generic.FormView):
    template_name = 'mnist/upload.html'
    form_class = ImageUploadForm

    def form_valid(self, form):
        # アップロードファイル本体を取得
        file = form.cleaned_data['file']

        # ファイルを、28*28にリサイズし、グレースケール(モノクロ画像)
        img = Image.open(file).resize((28, 28)).convert('L')

        # 学習時と同じ形に画像データを変換する
        img_array = np.asarray(img) / 255
        img_array = img_array.reshape(1, 784)

        # 推論した結果を、テンプレートへ渡して表示
        context = {
            'result': predict(img_array),
        }
        return render(self.request, 'mnist/result.html', context)


class PaintView(generic.TemplateView):
    template_name = 'mnist/paint.html'

    def post(self, request):
        base_64_string = request.POST['img-src'].replace(
            'data:image/png;base64,', '')
        file = BytesIO(base64.b64decode(base_64_string))

        # ファイルを、28*28にリサイズし、グレースケール(モノクロ画像)
        img = Image.open(file).resize((28, 28)).convert('L')

        # 学習時と同じ形に画像データを変換する
        img_array = np.asarray(img) / 255
        img_array = img_array.reshape(1, 784)

        # 推論した結果を、テンプレートへ渡して表示
        context = {
            'result': predict(img_array),
        }
        return render(self.request, 'mnist/result.html', context)

mnist/templates/mnist/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>手書き数字判別アプリ</title>
  </head>
  <body>
    <div class="container">
      <!-- ナビバー -->
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mnist:upload' %}">アップロード</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mnist:paint' %}">お絵かき</a>
        </li>
      </ul>

      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

mnist/templates/mnist/paint.html
{% extends 'mnist/base.html' %}

{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
<canvas id="canvas" width="140" height="140"></canvas>
<hr>
<input type="hidden" name="img-src" value="" id="img-src">
<input type="button" class="btn btn-outline-primary btn-lg" id="send" value="送信する">
{% csrf_token %}
</form>
{% endblock %}

{% block extrajs %}
<script>
// キャンバスを操作するためのオブジェクトを取得
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");

// キャンバスを黒く塗りつぶす
ctx.fillStyle = '#000';
ctx.fillRect(0, 0, 140, 140);

ctx.lineCap = 'square';  // 四角い形の線
ctx.strokeStyle = '#fff';  // 白い線
ctx.lineWidth = 13;  // 線の幅
var draw = false;  // クリック中かのフラグ

// マウスが動いたときに呼び出される
canvas.addEventListener("mousemove",function(e) {
  var rect = e.target.getBoundingClientRect();
  mouseX = e.clientX - rect.left;
  mouseY = e.clientY - rect.top;

  if(draw) {
    ctx.beginPath();
    ctx.moveTo(mouseX1,mouseY1);
    ctx.lineTo(mouseX,mouseY);
    ctx.stroke();
    mouseX1 = mouseX;
    mouseY1 = mouseY;
  }
});

// クリックで呼び出される
canvas.addEventListener("mousedown",function(e) {
  draw = true;
  mouseX1 = mouseX;
  mouseY1 = mouseY;
});

// クリックを離されると呼び出される
canvas.addEventListener("mouseup", function(e){
  draw = false;
});


// 送信ボタンで呼び出される
$('#send').on('click',function(e){
    var form = $(this).parents('form');
    var src = canvas.toDataURL('image/png');
    $('#img-src').val(src);
    form.submit();
});
</script>
{% endblock %}

mnist/templates/mnist/result.html
{% extends 'mnist/base.html' %}
{% block content %}
<p>{{ result }} と判別されました。</p>
{% endblock %}

mnist/templates/mnist/upload.html
{% extends 'mnist/base.html' %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
  {{ form.file }}<hr>
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-primary btn-lg" value="送信する">
</form>
{% endblock %}